[2025-07-19T03:18:27.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T03:18:27.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_dag.call_weather_rest_api scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T03:18:27.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_dag.call_weather_rest_api scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T03:18:27.802+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-19T03:18:27.984+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_weather_rest_api> on 2025-07-18 00:00:00+00:00
[2025-07-19T03:18:28.009+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2025-07-19T03:18:28.021+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_dag', 'call_weather_rest_api', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '1034', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmpza2132nd']
[2025-07-19T03:18:28.029+0000] {standard_task_runner.py:91} INFO - Job 1034: Subtask call_weather_rest_api
[2025-07-19T03:18:28.291+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_dag.call_weather_rest_api scheduled__2025-07-18T00:00:00+00:00 [running]> on host f4157e5fc51c
[2025-07-19T03:18:28.844+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_dag' AIRFLOW_CTX_TASK_ID='call_weather_rest_api' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-19T03:18:28.849+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T03:18:28.976+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-07-19T03:18:30.342+0000] {logging_mixin.py:188} INFO - S3 client initialized.
[2025-07-19T03:18:30.512+0000] {logging_mixin.py:188} INFO - city,timestamp,weather_main,weather_description,temp,feels_like,humidity,wind_speed,clouds
New York,1752894401,Clear,clear sky,20.63,20.6,71,2.73,5
[2025-07-19T03:18:30.726+0000] {logging_mixin.py:188} INFO - CSV uploaded to S3 at weather_data/unprocessed//weather_20250719031830.csv
[2025-07-19T03:18:30.728+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-19T03:18:30.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T03:18:30.752+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_dag, task_id=call_weather_rest_api, run_id=scheduled__2025-07-18T00:00:00+00:00, execution_date=20250718T000000, start_date=20250719T031827, end_date=20250719T031830
[2025-07-19T03:18:30.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-19T03:18:30.897+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2025-07-19T03:18:30.957+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-19T03:18:30.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
