[2025-09-20T04:41:51.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-20T04:41:51.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 4_logistics_ticket_classifier_full_dag.fetch_snowflake_data manual__2025-09-18T10:55:18.311962+00:00 [queued]>
[2025-09-20T04:41:51.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 4_logistics_ticket_classifier_full_dag.fetch_snowflake_data manual__2025-09-18T10:55:18.311962+00:00 [queued]>
[2025-09-20T04:41:51.553+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-20T04:41:51.680+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_snowflake_data> on 2025-09-18 10:55:18.311962+00:00
[2025-09-20T04:41:51.703+0000] {standard_task_runner.py:63} INFO - Started process 181 to run task
[2025-09-20T04:41:51.713+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '4_logistics_ticket_classifier_full_dag', 'fetch_snowflake_data', 'manual__2025-09-18T10:55:18.311962+00:00', '--job-id', '1095', '--raw', '--subdir', 'DAGS_FOLDER/4_logistics_ticket_classifier_full_dag.py', '--cfg-path', '/tmp/tmpvpv56_12']
[2025-09-20T04:41:51.726+0000] {standard_task_runner.py:91} INFO - Job 1095: Subtask fetch_snowflake_data
[2025-09-20T04:41:51.987+0000] {task_command.py:426} INFO - Running <TaskInstance: 4_logistics_ticket_classifier_full_dag.fetch_snowflake_data manual__2025-09-18T10:55:18.311962+00:00 [running]> on host 9d1b71842418
[2025-09-20T04:41:52.325+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='4_logistics_ticket_classifier_full_dag' AIRFLOW_CTX_TASK_ID='fetch_snowflake_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-18T10:55:18.311962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-18T10:55:18.311962+00:00'
[2025-09-20T04:41:52.329+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-20T04:41:52.385+0000] {connection.py:521} INFO - Snowflake Connector for Python Version: 3.17.3, Python Version: 3.11.9, Platform: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-09-20T04:41:52.389+0000] {connection.py:1464} INFO - Connecting to GLOBAL Snowflake domain
[2025-09-20T04:41:52.903+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2025-09-20T04:41:54.306+0000] {python.py:237} INFO - Done. Returned value was: Empty DataFrame
Columns: [TICKET_ID, CUSTOMER_ID, MESSAGE_TEXT, TICKET_CATEGORY]
Index: []
[2025-09-20T04:41:54.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-20T04:41:54.399+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=4_logistics_ticket_classifier_full_dag, task_id=fetch_snowflake_data, run_id=manual__2025-09-18T10:55:18.311962+00:00, execution_date=20250918T105518, start_date=20250920T044151, end_date=20250920T044154
[2025-09-20T04:41:54.532+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-20T04:41:54.631+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-20T04:41:54.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
