[2025-07-19T03:19:20.378+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-19T03:19:20.484+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_dag.copy_command_snowflake scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T03:19:20.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_dag.copy_command_snowflake scheduled__2025-07-18T00:00:00+00:00 [queued]>
[2025-07-19T03:19:20.524+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-19T03:19:20.612+0000] {taskinstance.py:2330} INFO - Executing <Task(SnowflakeOperator): copy_command_snowflake> on 2025-07-18 00:00:00+00:00
[2025-07-19T03:19:20.622+0000] {standard_task_runner.py:63} INFO - Started process 151 to run task
[2025-07-19T03:19:20.630+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_dag', 'copy_command_snowflake', 'scheduled__2025-07-18T00:00:00+00:00', '--job-id', '1037', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmpv_1wmvc4']
[2025-07-19T03:19:20.635+0000] {standard_task_runner.py:91} INFO - Job 1037: Subtask copy_command_snowflake
[2025-07-19T03:19:20.873+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_dag.copy_command_snowflake scheduled__2025-07-18T00:00:00+00:00 [running]> on host f4157e5fc51c
[2025-07-19T03:19:21.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_data_dag' AIRFLOW_CTX_TASK_ID='copy_command_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-18T00:00:00+00:00'
[2025-07-19T03:19:21.158+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-19T03:19:21.179+0000] {sql.py:276} INFO - Executing:   
            COPY INTO demo.demoschema.weather_data
            FROM @demo.demoschema.aws_demo_stage2/unprocessed/
            FILE_FORMAT = (FORMAT_NAME = demo.demoschema.weather_csv_format)
            PATTERN = '.*weather_.*\.csv';
       
[2025-07-19T03:19:21.217+0000] {base.py:84} INFO - Using connection ID 'snowflakeid' for task execution.
[2025-07-19T03:19:21.467+0000] {base.py:84} INFO - Using connection ID 'snowflakeid' for task execution.
[2025-07-19T03:19:21.471+0000] {connection.py:493} INFO - Snowflake Connector for Python Version: 3.16.0, Python Version: 3.11.9, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-07-19T03:19:21.475+0000] {connection.py:1410} INFO - Connecting to GLOBAL Snowflake domain
[2025-07-19T03:19:23.124+0000] {sql.py:470} INFO - Running statement: COPY INTO demo.demoschema.weather_data
            FROM @demo.demoschema.aws_demo_stage2/unprocessed/
            FILE_FORMAT = (FORMAT_NAME = demo.demoschema.weather_csv_format)
            PATTERN = '.*weather_.*\.csv';, parameters: None
[2025-07-19T03:19:23.890+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-19T03:19:23.892+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 395, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1137, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 279, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 334, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 210, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): 01bdc8c7-0000-26b6-002d-750b00031132: SQL compilation error:
Table 'DEMO.DEMOSCHEMA.WEATHER_DATA' does not exist
[2025-07-19T03:19:23.923+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_data_dag, task_id=copy_command_snowflake, run_id=scheduled__2025-07-18T00:00:00+00:00, execution_date=20250718T000000, start_date=20250719T031920, end_date=20250719T031923
[2025-07-19T03:19:24.019+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1037 for task copy_command_snowflake (001757 (42601): 01bdc8c7-0000-26b6-002d-750b00031132: SQL compilation error:
Table 'DEMO.DEMOSCHEMA.WEATHER_DATA' does not exist; 151)
[2025-07-19T03:19:24.062+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-19T03:19:24.103+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2025-07-19T03:19:24.129+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-19T03:19:24.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
